services:
  # Database Service
  db:
    image: postgres:16
    container_name: eight-db
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - eight-network

  # Server Service
  server:
    build:
      context: apps/server
      dockerfile: Dockerfile
    container_name: eight-server
    restart: unless-stopped
    env_file: .env
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
      DATABASE_HOST: db
      VALKEY_HOST: cache
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    networks:
      - eight-network


volumes:
  postgres-data:
    name: eight-postgres-data

networks:
  eight-network:
    driver: bridge